# Switched to 'midnight' Jekyll theme: https://github.com/pages-themes/midnight#usage
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one