# Switched to 'midnight' Jekyll theme: https://github.com/pages-themes/midnight#usage
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Fix [Link](README.md) => <a href="README.html">Link</a>
# - jekyll-relative-links
# - jekyll-optional-front-matter

# EXCLUDE FILES & FOLDERS FROM BUILD: 
exclude: 
  - resources/codecademy
  - app
  - components
  - public
  - tools
  - curriculum/week13
  - curriculum/week14
  - curriculum/week15
  - curriculum/week16
  - curriculum/week17
  - curriculum/week18
  - curriculum/week19
  - curriculum/week20
  - curriculum/week21
  - curriculum/week22
  - curriculum/week23
  - curriculum/week24
  - curriculum/week25
  - curriculum/week26
  - curriculum/week27
  - curriculum/week28
  - curriculum/week29
  - curriculum/week30
  - curriculum/week31
  - curriculum/week32
  - curriculum/week33
  - curriculum/week34
  - curriculum/week35
  - curriculum/week36
  - user/week13
  - user/week14
  - user/week15
  - user/week16
  - user/week17
  - user/week18
  - user/week19
  - user/week20
  - user/week21
  - user/week22
  - user/week23
  - user/week24
  - user/week25
  - user/week26
  - user/week27
  - user/week28
  - user/week29
  - user/week30
  - user/week31
  - user/week32
  - user/week33
  - user/week34
  - user/week35
  - user/week36
  
# CUSTOM _SASS FOLDER: https://github.com/jekyll/jekyll-sass-converter#configuration-options, https://jekyllrb.com/docs/configuration/sass/
sass:
  sass_dir: assets/jekyll/_sass

# CUSTOM _includes FOLDER: https://jekyllrb.com/docs/configuration/options/#build-command-options
layouts_dir:  assets/jekyll/_layouts
includes_dir: assets/jekyll/_includes

